---

- name: install epel-release
  yum:
    name: epel-release
    state: installed
- name: install nginx
  yum:
    name: nginx
    state: installed

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copy nginx configuration
  template:
    src: "../files/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
  notify: restart_nginx

- name: create site directory
  file:
    path: /opt/nginx/ansible
    state: directory
    recurse: yes

- name: create site content
  copy:
    src: "../files/index.php"
    dest: /opt/nginx/ansible/index.php