---

- name: create user
  user:
    name: user_ssh_key
    password: $6$KjyfytoJ$hoQdVIGcRZgje2HpHFf8ldvooLfY774SrEpHkADUf3d7uGBSwVLeMXsPIfb4l2TaXWvprMz868ZbH8HLaiDeh.
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048

- name: Deploy SSH Key
  authorized_key:
    user: user_ssh_key
    key: "{{ lookup('file', '/cygdrive/c/Users/User/.ssh/id_rsa.pub') }}"
    state: present