---
- hosts: test
  gather_facts: no
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
  - name: remove conf.d
    file:
      path: /etc/httpd/conf.d
      state: absent
  - name: create conf.d
    file:
      path: /etc/httpd/conf.d
      state: directory
  - name: add vhost
    copy:
      src: /etc/ansible/playbooks/files/vhost.conf
      dest: /etc/httpd/conf.d/host1.conf
    notify: restart_httpd
  - name: create site content
    copy:
      src: /etc/ansible/playbooks/files/site_content.html
      dest: /var/www/html/index.html

  handlers:
    - name: restart httpd
      listen: restart_httpd
      service:
        name: httpd
        state: restarted










