---
- hosts: test
  gather_facts: no
  become: yes
  tasks:
    - name: add signing key
      rpm_key:
        key: "https://download.docker.com/linux/centos/gpg"
        state: present
    - name: add repo into repo.d list
      yum_repository:
        name: docker
        description: docker repo
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/centos/gpg"
    - name: install docker
      yum:
        name:
          - yum-utils
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: true
    - name: start docker
      service:
        name: "docker"
        enabled: true
        state: started


