---

- hosts: test
  gather_facts: no
  become: yes
  tasks:
    - name: create user
      user:
        name: user1
        password: $6$KjyfytoJ$hoQdVIGcRZgje2HpHFf8ldvooLfY774SrEpHkADUf3d7uGBSwVLeMXsPIfb4l2TaXWvprMz868ZbH8HLaiDeh.
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048