---
- name: Install Nginx
  hosts: test_nginx
  gather_facts: no
  become: yes
  roles:
    - users
    - http


- name: Install Php
  hosts: test_php
  gather_facts: no
  become: yes
  roles:
    - users
    - php